### ISSUE TITLE
最后python oc.py时有错误

### ISSUE THREAD

**Issue by lhz7797251** [greatshi/antminer_auto_oc#1]
C:\antminer_auto_oc>python oc.py
Traceback (most recent call last):
  File "oc.py", line 93, in <module>
    main()
  File "oc.py", line 90, in main
    change_freq(ips, username, password, low_temp, high_temp, term)
  File "oc.py", line 64, in change_freq
    info = get_info(ip, auth)
  File "oc.py", line 23, in get_info
    res_data = urllib2.urlopen(url_status).read()
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\ProgramData\Anaconda2\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] >

不知道什么原因，麻烦指正下，我的QQ314798268

**Comment by greatshi** [comment]
到这一步，通过网页操作就可以了，python manage.py runserver
检测矿机的ip与密码
